version: "3"
services:
  nginx:
    image: gregorwebmaster/ngino
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./data/www:/var/www
      - ./config/nginx/vhosts:/etc/nginx/vhosts
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php71
  php71:
    image: gregorwebmaster/alpine-php7
    volumes:
      - ./config/php71/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./data/www:/var/www
      - ./logs/php:/var/log/php
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7.19
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourRootPassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8855:80
    volumes:
      - /sessions
  redis:
    image: redis:4.0.1-alpine
